#===============================================================================#
# __          __   _ _      _         _   _            _____           _        #
# \ \        / /  | | |    (_)       | | | |          |  __ \         | |       #
#  \ \  /\  / /_ _| | | __  _ _ __   | |_| |__   ___  | |__) |_ _ _ __| | __    #
#   \ \/  \/ / _` | | |/ / | | '_ \  | __| '_ \ / _ \ |  ___/ _` | '__| |/ /    #
#    \  /\  / (_| | |   <  | | | | | | |_| | | |  __/ | |  | (_| | |  |   <     #
#     \/  \/ \__,_|_|_|\_\ |_|_| |_|  \__|_| |_|\___| |_|   \__,_|_|  |_|\_\    #
#               |  ____|                          | |        | |                #
#               | |__  __  ___ __   __ _ _ __   __| | ___  __| |                #
#               |  __| \ \/ / '_ \ / _` | '_ \ / _` |/ _ \/ _` |                #
#               | |____ >  <| |_) | (_| | | | | (_| |  __/ (_| |                #
#               |______/_/\_\ .__/ \__,_|_| |_|\__,_|\___|\__,_|                #
#                           | |                                                 #
#                           |_|                                                 #
#===============================================================================#

#===============================================================================#
#                                                                               #
#                             (c) Efnilite MMXX-MMXXI                           #
#                                                                               #
#===============================================================================#

# Whether to enable cube mode. You can set this up in-game using /witpex
cuboid-mode: true

# Send back after multiplayer
# Whether players should be sent back to their previous data/location after they finish a multiplayer match.
# If this is set to false, they will join a regular singleplayer WITP game.
send-back-after-multiplayer: false

# Options for styles
styles:
    enabled: true

    list:
        medieval: [spruce_planks, cobblestone, spruce_wood, stone_bricks, mossy_stone_bricks]
        christmas: [snow_block, sea_lantern, spruce_leaves, red_wool]
        fall: [brown_mushroom_block, red_mushroom_block, mushroom_stem, carved_pumpkin, pumpkin]
        city: [smooth_stone, bricks, stone_brick, cyan_terracotta]

# Options for the modes
modes:

    hourglass:
        enabled: true

    practice:
        enabled: true

    speed:
        enabled: true
        # Level 3 = speed 3
        effect-level: 3

    teamsurvival:
        enabled: true

    timetrial:
        enabled: true