name: 'IPPlus'
author: Efnilite
version: 1.0.2
api-version: 1.16
description: "The premium addon for Infinite Parkour."
depend: ['vilib', 'IP']
main: dev.efnilite.ipp.IPP
commands:
    ipp:
        description: "The main command for Infinite Parkour Plus"
        aliases: [ipplus]